require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe AgendamentosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Agendamento. As you add validations to Agendamento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      data: DateTime.now(),
      local_id:  FactoryBot.create(:local).id,
      especialidade_id: FactoryBot.create(:especialidade).id,
      medico_id:  FactoryBot.create(:medico).id,
      usuario_id: FactoryBot.create(:usuario).id
    }
  }

  let(:invalid_attributes) {
    {
      data: nil,
      local_id:  nil,
      especialidade_id: nil,
      medico_id:  nil,
      usuario_id: nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AgendamentosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      Agendamento.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      agendamento = Agendamento.create! valid_attributes
      get :show, params: {id: agendamento.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      agendamento = Agendamento.create! valid_attributes
      get :edit, params: {id: agendamento.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Agendamento" do
        expect {
          post :create, params: {agendamento: valid_attributes}, session: valid_session
        }.to change(Agendamento, :count).by(1)
      end

      it "redirects to the created agendamento" do
        post :create, params: {agendamento: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Agendamento.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {agendamento: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
          data: DateTime.now(),
          local_id:  FactoryBot.create(:local).id,
          especialidade_id: FactoryBot.create(:especialidade).id,
          medico_id:  FactoryBot.create(:medico).id,
          usuario_id: FactoryBot.create(:usuario).id
        }
      }

      it "updates the requested agendamento" do
        agendamento = Agendamento.create! valid_attributes
        old_medico = agendamento.medico.id
        old_usuario = agendamento.usuario.id
        old_local = agendamento.local.id
        old_especialidade = agendamento.especialidade.id

        put :update, params: {id: agendamento.to_param, agendamento: new_attributes}, session: valid_session
        agendamento.reload
        expect(agendamento.medico.id).to_not be_equal(old_medico)
        expect(agendamento.usuario.id).to_not be_equal(old_usuario)
        expect(agendamento.local.id).to_not be_equal(old_local)
        expect(agendamento.especialidade.id).to_not be_equal(old_especialidade)

      end

      it "redirects to the agendamento" do
        agendamento = Agendamento.create! valid_attributes
        put :update, params: {id: agendamento.to_param, agendamento: valid_attributes}, session: valid_session
        expect(response).to redirect_to(agendamento)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        agendamento = Agendamento.create! valid_attributes
        put :update, params: {id: agendamento.to_param, agendamento: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested agendamento" do
      agendamento = Agendamento.create! valid_attributes
      expect {
        delete :destroy, params: {id: agendamento.to_param}, session: valid_session
      }.to change(Agendamento, :count).by(-1)
    end

    it "redirects to the agendamentos list" do
      agendamento = Agendamento.create! valid_attributes
      delete :destroy, params: {id: agendamento.to_param}, session: valid_session
      expect(response).to redirect_to(agendamentos_url)
    end
  end

end
