# coding: iso-8859-1
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe EspecialidadesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Especialidade. As you add validations to Especialidade, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      Nome:"Cardiologista" ,
      Descricao:"Médico especialista" , 
      ativo:true
    }
  }

  let(:invalid_attributes) {
    {
      Nome:nil,
       Descricao:"Teste sem a propriedade nome" , 
       ativo:nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EspecialidadesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      Especialidade.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      especialidade = Especialidade.create! valid_attributes
      get :show, params: {id: especialidade.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      especialidade = Especialidade.create! valid_attributes
      get :edit, params: {id: especialidade.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Especialidade" do
        expect {
          post :create, params: {especialidade: valid_attributes}, session: valid_session
        }.to change(Especialidade, :count).by(1)
      end

      it "redirects to the created especialidade" do
        post :create, params: {especialidade: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Especialidade.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {especialidade: invalid_attributes}, session: valid_session
       expect(response.status).to eq(200)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
       {
          Nome:"Clinico geral",
           Descricao:"Medico do tipo clinico geral"
        }
      }

      it "updates the requested especialidade" do
        especialidade = Especialidade.create! valid_attributes
        put :update, params: {id: especialidade.to_param, especialidade: new_attributes}, session: valid_session
        especialidade.reload
        expect(response.status).to eq(302)
      end

      it "redirects to the especialidade" do
        especialidade = Especialidade.create! valid_attributes
        put :update, params: {id: especialidade.to_param, especialidade: valid_attributes}, session: valid_session
        expect(response).to redirect_to(especialidade)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        especialidade = Especialidade.create! valid_attributes
        put :update, params: {id: especialidade.to_param, especialidade: invalid_attributes}, session: valid_session
        expect(response.status).to eq(200)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested especialidade" do
      especialidade = Especialidade.create! valid_attributes
      expect {
        delete :destroy, params: {id: especialidade.to_param}, session: valid_session
      }.to change(Especialidade, :count).by(-1)
    end

    it "redirects to the especialidades list" do
      especialidade = Especialidade.create! valid_attributes
      delete :destroy, params: {id: especialidade.to_param}, session: valid_session
      expect(response).to redirect_to(especialidades_url)
    end
  end

end
